### ISSUE TITLE
Program not able to parse string ratios to float

### ISSUE THREAD

**Issue by AlgumCorrupto** [unremarkablegarden/scala2mts#1]
I'm having this error while trying to convert a scala file to MTS, its giving me an error in the line 175 called ``could not convert string to float: '2/1'``

**Comment by AlgumCorrupto** [comment]
here's the error 
![image](https://user-images.githubusercontent.com/112904295/236953207-0db543a2-1e38-4e37-b86c-a93500c9d619.png)

**Comment by unremarkablegarden** [comment]
Thank you. Please provide your scl file, and python version.

**Comment by unremarkablegarden** [comment]
And python version...

**Comment by maximejerryfraisse** [comment]
same problem. any solution?

**Comment by unremarkablegarden** [comment]
Provide the scl file and Python version please

**Comment by maximejerryfraisse** [comment]
the file : [12ET.scl.zip](https://github.com/unremarkablegarden/scala2mts/files/11850100/12ET.scl.zip) / Python 3.11

but I think that's clear. just need to replace `2/1` by `1200.` or `2.` right?

**Comment by unremarkablegarden** [comment]
This is fixed now
